[goldeneye]
output_root = "_output"

[render]
renderer = "typhoon"
output_pattern = "{path}.exr"

[renderers.typhoon]
command = [
    "pixi", "run",
    "--manifest-path", "../openusd-omniverse/pixi.toml",
    "--clean-env",
    "usdrender",
    "{usd_path}",
    "--outputRoot", "{suite_output_root}",
]

[renderers.typhoon-local]
command = [
    "pixi", "run",
    "--manifest-path", "../openusd-omniverse/pixi.toml",
    "--clean-env",
    "usdrender",
    "{usd_path}",
    "--outputRoot", "{suite_output_root}",
]


[renderers.arnold]
command = [
    "kick", "{usd_path}",
    "-od", "{suite_output_root}",
    "-set", "options.abort_on_license_fail", "off",
    "-set", "options.skip_license_check", "on",
    "-set", "driver_exr.tiled", "false",
    "-dw",
    "-dp",
    "-r", "256", "256",
]
