[workspace]
name = "typhoon-test-suite"
platforms = ["linux-64", "osx-arm64", "win-64"]
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
channel-priority = "disabled"

[dependencies]
python = "3.11.*"
openusd-typhoon = "*"
pytest = "*"
numpy = "*"
pillow = "*"
goldeneye = ">=0.9.0"

[pypi-dependencies]
flip-evaluator = "==1.7"
# goldeneye = { path = "../goldeneye", editable = true }

[tasks]
"download-references" = "goldeneye download-references"
"update-references" = "goldeneye update-references"
"extract-failures" = "goldeneye extract-failures"
"view" = "goldeneye view"
